import GFNBounds.Balance.LocalConvergenceClose
import GFNBounds.Balance.LocalConvergenceMixing
import GFNBounds.Graph.MorozovDB
import GFNBounds.Balance.RemarksA

/-!
# The DB instance of the training-speed theorem: a local rate through the edge lift, wherever the lifted mixing sum is finite

**`theo:training_speed`** — `cv_divergence.tex:69–82`; **its last clause only**, the
detailed-balance sentence (`:79–81`). The rest of the theorem is certified through its full form
`theo:training_speed_full` (`DiscreteGlobal.training_speed_full_complete`); the map row recorded
this clause as the one without Lean ("no `K₂` instance").

> (`theo:training_speed`) On a finite marked graph with a frozen backward policy positive on the
> edges of its loop closure, and for a training measure of uniformly positive density, gradient
> training of the state-space balance loss generated by `(log x)²` — the generator of the
> practical DB and TB losses — converges to a balanced flow from *every* positive
> initialization, […]. No mixing, spectral-gap or aperiodicity hypothesis is used for this
> state-space loss; **the DB instance inherits a local rate through the edge lift wherever the
> lifted mixing sum is finite (Theorems `theo:db_stable_frozen` and `theo:local_convergence`).**

> (the section's setting, `cv_divergence.tex:63`) Let `G` be a finite path-connected marked
> graph, let the frozen backward policy be positive on the edges of the loop closure `Ĝ` […]

The two theorems the sentence cites, and what they say of the DB loss:

> (`theo:db_stable_frozen`, `cv_divergence.tex:159–165`) For a training measure of uniformly
> positive density, a backward policy with summable mixing makes gradient descent on the
> *linearized* FM and DB losses with frozen backward policy converge to the balanced ray at an
> explicit exponential rate, provided the step size stays below an explicit cap; the
> linearization conserves the total flow normalization along the way. […]
> (`:166`) The rate is `ϱ = g''(1)w_min/B̂²` with `B̂` the mixing sum, which for the FM loss is
> `B` itself and for DB is `1+B`.

> (`theo:local_convergence`, `cv_divergence.tex:170–174`) On a finite state space, and from an
> explicit neighbourhood of the unit-mass balanced flow, the rate above upgrades to the full
> nonlinear dynamics: halved for the gradient flow, and quartered for gradient descent below an
> explicit step.

> (`theo:db_stable_frozen_full`, `proofs.tex:653`) […] with step `ε ≤ (4g''(1)‖w‖_{L^∞})^{−1}`,
> the contraction factor per step is `1−εϱ`. For the FM loss `T=π_←`, and for the DB loss `T=K₂`
> with `λ₂` in place of `λ` (Definition `def:edge_lift`). When `π_←` has summable `L²`-mixing,
> `B:=∑_{n≥0}β_n<∞` […], `B̂:=∑_{n≥0}β̂_n` […] is a coercivity constant of `T` with `B̂≥1`,
> equal to `B` for the FM loss and to `1+B` for the DB loss

**What "the lifted mixing sum is finite" is, here.** `K₂` is the edge lift of the loop closure
`π̂_←`, taken on `E = {(s,s') : π̂_←(s'→s) > 0}` with its invariant probability `λ₂`, as
`theo:local_convergence_full` takes the DB instance (`proofs.tex:667`); `P₂`, `Π₂` are its density
action and mean projection on `L²(λ₂)`. The lifted mixing sum is `B̂₂ := ∑_{n≥0}‖P₂ⁿ − Π₂‖`
(`liftedMixingSum`), and "is finite" is `hsum : Summable (n ↦ ‖P₂ⁿ − Π₂‖)` — the paper's own gloss
of `B̂ < +∞` in `lem:sigma_mixing` (`proofs.tex:629`, "(summable `L²`-mixing)"), and equivalent to
`∑ₙ‖P₂ⁿ − Π₂‖ ≠ ∞` in `ℝ≥0∞` (`lifted_summable_iff_ne_top`).

## What is proved

| | |
|---|---|
| `nontrivial_edgeSet` | `E` has two distinct pairs — the wrap pair `(s_f,s₀)` and a pair `(y,s_f)` — for **every** backward policy, so `β̂₀ = 1` needs no hypothesis |
| `liftedMixingSum` | `B̂₂ := ∑_{n≥0}‖P₂ⁿ − Π₂‖_{L²(λ₂)}`, i.e. `Core.Mixing.B (densOp λ₂ K₂) (meanOp λ₂)` |
| `lifted_beta_succ`, **`lifted_summable_iff`**, **`liftedMixingSum_eq`** | `lem:lift_mixing` on the graph, `β̂_{n+1} = β_n`: the lifted sum is finite **iff** the backward chain has summable mixing, and then `B̂₂ = 1 + B` (`proofs.tex:589`, `:653`) |
| `summable_iff_tsum_ofReal_ne_top`, **`lifted_summable_iff_ne_top`** | "is finite" read literally, in `ℝ≥0∞` |
| **`training_speed_DB_edge_lift`** | **the sentence**, one statement: the DB loss is the balance loss of `K₂` on `(E,λ₂)`; `B̂₂ ≥ 1` is a coercivity constant; `B̂₂ = 1 + B`; `ϱ = g''(1)w_min/B̂₂² = 2w_min/B̂₂² > 0`; `theo:db_stable_frozen`'s two linearized clauses for the DB loss at `B̂₂`; `theo:local_convergence`'s whole conclusion for the DB loss at `B̂₂` (`LocalConvergenceClose.local_convergence_full_DB_paper`) |
| `wrapInd`, `wrapInd_ne_const`, `eq_const_of_balanced_edge`, `eq_zero_of_nrmL2_eq_zero` | the indicator of the wrap pair is not constant; under `hsum` a balanced density on `E` is constant (summable mixing is ergodicity, `LocalConvergenceMixing.eq_const_of_densAct_eq`) |
| **`training_speed_DB_edge_lift_nonvacuous`** | non-vacuity on **every** instance (kb 0025, 0027): admissible linearized steps exist and both linearized dynamics run from `𝟙_{(s_f,s₀)}`, whose deviation from its mean is non-zero; the nonlinear DB flow from `ε₀𝟙_{(s_f,s₀)}` starts **off balance** and converges to a balanced flow |
| **`triangle_DB_edge_lift_check`** | the bundle, `hsum` included, is inhabited: on the aperiodic triangle of `RemarksA`, with its invariant probability and `w ≡ 1` |
| **`lifted_not_summable_of_leveled`**, **`ar_lifted_not_summable`** | "wherever" is a genuine restriction: on a leveled (autoregressive) graph the lifted sum is `+∞` |
| **`lifted_summable_iff_aperiodic`** | "wherever" made exact: the lifted sum is finite **iff** the loop closure `π̂_←` is aperiodic (`RemarksA.graphs_vs_L2_aperiodic`, `graphs_vs_L2_periodic`) — summable mixing **is** aperiodicity on these chains |

## Hypothesis checklist

| paper | here |
|---|---|
| finite marked graph | ✓ `G : Graph.MarkedGraph V`, `[Fintype V] [DecidableEq V]` |
| path-connected (`cv_divergence.tex:63`, `def:path_connected`) | ✓ `hpc : G.PathConnected` |
| frozen backward policy positive on the edges of its loop closure | ✓ `B : Graph.BackwardPolicy G`, `hpos : B.PositiveOnEdges`; the loop closure is `B.phat`, which carries the wrap edge with mass `1` by construction (`phat_src_snk`) |
| `λ` the backward chain's invariant measure | ✓ `hl : B.IsInvProb lam`; `λ > 0` is derived (`IsInvProb.pos`) |
| "the DB instance", "through the edge lift" (`def:edge_lift`, `prop:db_lift`) | ✓ `T = K₂ = edgeKernelE B.phat`, `λ₂ = edgeMeasureE B.phat lam` on `E = EdgeSet B.phat`; `K₂` Markov, `λ₂` an invariant positive probability (`Graph.edge_setting`); that the balance loss of `K₂` on `(E,λ₂)` **is** the DB loss of `(m₁μ, π_→^μ)` is the first conjunct (`C3Wrappers.loss_edgeE_eq_db`) |
| training measure of uniformly positive density | ✓ `ν̂ = wλ₂` on `E`: `w : EdgeSet B.phat → ℝ`, `hwmin0 : 0 < wmin`, `hwmin : ∀ e, wmin ≤ w e`; `‖w‖_{L^∞}` is the actual `supAbsOf w` |
| the generator `(log x)²` | ✓ `logSq`, driven by `logSqDeriv` (its derivative at every `x > 0`), `g''(1) = deriv (deriv logSq) 1 = 2` (the rate conjunct), `a = 1/2` (the window `theo:training_speed_full`*2* uses) |
| "wherever the lifted mixing sum is finite" | ✓ `hsum`; `⇔` `ℝ≥0∞`-finiteness (`lifted_summable_iff_ne_top`); `⇔` summable mixing of `π̂_←` (`lifted_summable_iff`), the hypothesis of `theo:db_stable_frozen` |
| `theo:db_stable_frozen` for DB: `B̂ ≥ 1` a coercivity constant, `B̂ = 1+B`, `ϱ = g''(1)w_min/B̂²` | ✓ conjuncts 2–7, at `B̂ = B̂₂` — `B̂₂ ≥ 1` and the coercivity **derived** (`one_le_B_densOp`, `mixing_coercivity_finite`), not hypothesised |
| … linearized descent, step `ε ≤ (4g''(1)‖w‖_{L^∞})^{−1}`: `Πh` conserved, contraction `1 − εϱ` | ✓ conjunct 8, the cap in its printed form; ⚠ `0 ≤ ε` (a step `0` is allowed, trivially) |
| … linearized flow `ḣ = −Hh`: `Πh_t` conserved, `‖h_t − Πh_t‖ ≤ e^{−ϱt}‖h₀ − Πh₀‖` | ✓ conjunct 9; ⚠ the ODE is asked at every real `t` — see SCOPE |
| `theo:local_convergence` for DB: from an explicit neighbourhood, rate halved for the flow, quartered for descent below an explicit step | ✓ conjuncts 10–12: `local_convergence_full_DB_paper`'s whole conclusion at `B̂ = B̂₂`, `g = logSq`, `gd = logSqDeriv`, `a = 1/2` — `λ_min = min_E λ₂` exactly, `C_∞ ≥ 1`, `ε₀ ∈ (0, a/(16C_∞)]`, `C ≥ 1`, `γ₀ > 0` as printed formulas; from every `‖h₀‖_{L²(λ₂)} ≤ ε₀` the DB gradient flow **exists**, its field **is** the `L²(λ₂)` gradient of the DB loss, it is positive, unique, and converges to a balanced `c_∞λ₂` at `2e^{−ϱt/2}`; descent with `0 < γ ≤ γ₀` is well defined and contracts by `1 − γϱ/4` |
| "no … aperiodicity hypothesis" — said by the paper of the **state-space** loss, not of this sentence | ⚠ **carried here, as `hsum`**: on these chains `hsum` ⇔ `π̂_←` aperiodic (`lifted_summable_iff_aperiodic`), so the DB sentence brings back the hypothesis the clause before it avoids; it holds on the aperiodic triangle (`triangle_DB_edge_lift_check`) and fails on every periodic loop closure, leveled graphs among them (`lifted_not_summable_of_leveled`) |
| the DB ratio's orientation (`prop:db_lift`, `proofs.tex:540`: the usual ratio is the reciprocal, "immaterial for `g` symmetric such as `(log x)²`") | ✓ the first conjunct writes the DB loss in the paper's orientation; `(log x)² = (log (1/x))²` (`Real.log_inv`) |

## SCOPE (disclosed)

* **Only the DB sentence.** The state-space-loss clauses of `theo:training_speed` ("converges …
  from *every* positive initialization", both phases, flow and descent, "no mixing, spectral-gap
  or aperiodicity hypothesis") are its twin's, `DiscreteGlobal.training_speed_full_complete`; they
  are not restated here.
* **`E`, not `𝒮²`.** `theo:db_stable_frozen_full` states the DB instance with `K₂`, `λ₂` on `𝒮²`,
  `theo:local_convergence_full` on `E`; both are stated here on `E`, where `λ₂ > 0` and the
  weighted `L²` is an honest inner-product space. `λ₂` vanishes off `E`, so `L²(λ₂)` on `𝒮²` and on
  `E` are the same space, and the mixing coefficients do not change on restriction
  (`LiftFinite.opNorm_densDeviation_restrict`) — as disclosed by `MorozovDB.lean`.
* **The linearized dynamics are hypothesised**, as `theo:db_stable_frozen_full` itself states them
  ("along the linearized gradient flow", "for the linearized gradient descent"), and the
  identification of `H = g''(1)A^†M_wA` with the linearization of the DB loss's gradient is
  `Expansion.gd_diffusion_display`'s — stated for any finite Markov kernel with a positive invariant
  probability, so for `K₂` on `E` through `Graph.edge_setting` — and, on the general layer,
  `GdDiffusionGeneral.theo_gd_diffusion_DB`'s; it is not re-proved here. **The linearized flow is asked at every real
  `t`**, as `WeightedL2.stable_frozen_decay_finite` and `MorozovDB.stable_frozen_decay_DB_sigma`
  ask it, the conclusion at `t ≥ 0`. This is not kb 0025's vacuity: the ODE is linear and
  `Graph.exists_linFlow` solves it on all of `ℝ` from every `h₀` (`e^{−tH}h₀`), and
  `training_speed_DB_edge_lift_nonvacuous` runs it from an unbalanced start. A curve solving it on
  `[0,∞)` only is covered once extended by `e^{−tH}` below `0`, which is not formalized.
* **`B̂₂` is the library's `Core.Mixing.B`** of `densOp λ₂ K₂`, `meanOp λ₂` on `EuclideanSpace ℝ E`,
  whose operator norm is the `L²(λ₂)` one through the weighting isometry (`WeightedL2Norm.lean`),
  and `hsum` is exactly `Core.Mixing` at those operators
  (`LocalConvergenceMixing.mixing_densOp_iff_summable`).
* **`2 * (1 / 2) / 3`** in conjunct 12 is `local_convergence_full_DB_paper`'s `2a/3` at `a = 1/2`,
  left as instantiated: every ratio stays within `1/3` of `1`.
* **`hsum` is a genuine restriction**, not a formality: it **is** aperiodicity of `π̂_←`
  (`lifted_summable_iff_aperiodic`), so on every periodic loop closure — leveled, autoregressive
  graphs among them (`lifted_not_summable_of_leveled`, `ar_lifted_not_summable`) — the lifted sum is
  infinite and the sentence says nothing. The DB local rate on such graphs is
  `prop:morozov_rate`*(3)*'s, at `1 + B̂_σ` (`MorozovDB.local_convergence_full_DB_sigma`), a
  different statement, which needs no aperiodicity.
* **One window**, `a = 1/2`, as the twin takes it; "a local rate" asks no more. The nonlinear
  descent's non-vacuity is by its recursion (`γ₀ > 0` is a conjunct); it is not exhibited.
* **Inhabitation (kb 0025).** `triangle_DB_edge_lift_check`: on `RemarksA`'s triangle
  (`s₀ → x → s_f`, `s₀ → s_f`; returns to `s₀` of lengths `2` and `3`, aperiodic), with its
  invariant probability, `w ≡ 1`, `w_min = 1`, the backward chain has summable mixing
  (`RemarksA.graphs_vs_L2_aperiodic`, via Schur's theorem, not effective), hence so does the edge
  chain, and `B̂₂ = 1 + B`. `training_speed_DB_edge_lift_nonvacuous`, on every instance: the
  largest admissible linearized step is positive, the linearized descent and flow run from
  `𝟙_{(s_f,s₀)}`, whose deviation from its mean has positive norm, and the nonlinear flow from
  `ε₀𝟙_{(s_f,s₀)}` — inside the paper's ball, `ε₀ > 0` — is **not** balanced at `t = 0` and
  converges to a balanced flow. So neither the hypotheses nor the conclusions are empty.
* **`sorry`-free**; axioms `[propext, Classical.choice, Quot.sound]`.

Provenance: mathlib `fabf563a` (tag `v4.31.0`), pinned via `lakefile.toml`.
-/

namespace GFNBounds.Balance.TrainingSpeedDB

open Finset Filter Topology

/-! ### The lifted mixing sum -/

section EdgeLift

variable {V : Type*} [Fintype V] [DecidableEq V] {G : Graph.MarkedGraph V}

/-- The edge set `E = {(s,s') : π̂_←(s'→s) > 0}` of the loop closure has two distinct pairs, for
every backward policy: the wrap pair `(s_f, s₀)`, and a pair `(y, s_f)` with `π̂_←(s_f → y) > 0`,
which exists because the row of `π̂_←` at `s_f` sums to `1`. The two differ in their second
coordinate, `s₀ ≠ s_f`. -/
theorem nontrivial_edgeSet (B : Graph.BackwardPolicy G) : Nontrivial (EdgeSet B.phat) := by
  obtain ⟨y, hy⟩ : ∃ y, 0 < B.phat G.snk y := by
    by_contra hcon
    have hle : ∀ y, B.phat G.snk y ≤ 0 := fun y => not_lt.mp fun h => hcon ⟨y, h⟩
    have h0 : ∑ y, B.phat G.snk y ≤ 0 := Finset.sum_nonpos fun y _ => hle y
    rw [B.phat_row_sum] at h0
    norm_num at h0
  exact ⟨⟨Graph.wrapEdge B, ⟨(y, G.snk), hy⟩, fun h =>
    G.src_ne_snk (congrArg (fun e : EdgeSet B.phat => e.1.2) h)⟩⟩

/-- **`theo:training_speed`, "the lifted mixing sum"** (`cv_divergence.tex:79–81`):
`B̂₂ := ∑_{n≥0}‖P₂ⁿ − Π₂‖_{L²(λ₂)}`, the mixing sum of the edge lift `K₂` of the loop closure
`π̂_←`, on `E` with its invariant probability `λ₂`. `P₂` and `Π₂` are the density action and the
mean projection conjugated onto `EuclideanSpace ℝ E` by the weighting isometry, so the norm is the
`L²(λ₂)` operator norm (`WeightedL2Norm.lean`). -/
noncomputable def liftedMixingSum (B : Graph.BackwardPolicy G) (lam : V → ℝ) : ℝ :=
  Core.Mixing.B (densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat))
    (meanOp (edgeMeasureE B.phat lam))

variable {B : Graph.BackwardPolicy G} {lam : V → ℝ}

/-- `lem:lift_mixing` on the loop closure of a marked graph: `β̂_{n+1} = β_n`, the lifted
coefficient against the backward chain's (`LiftFinite.lift_mixing_beta` at `π̂_←`). -/
theorem lifted_beta_succ (hpc : G.PathConnected) (hpos : B.PositiveOnEdges)
    (hl : B.IsInvProb lam) (n : ℕ) :
    Core.Mixing.beta (densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat))
        (meanOp (edgeMeasureE B.phat lam)) (n + 1)
      = Core.Mixing.beta (densOp lam B.phat) (meanOp lam) n :=
  lift_mixing_beta B.phat_nonneg B.phat_row_sum (hl.pos hpc hpos) hl.inv hl.total n

/-- **`theo:training_speed`, "wherever the lifted mixing sum is finite"**: the lifted mixing sum
is finite exactly when the backward chain has summable `L²`-mixing — the hypothesis of
`theo:db_stable_frozen` — since `β̂_{n+1} = β_n` (`lem:lift_mixing`). -/
theorem lifted_summable_iff (hpc : G.PathConnected) (hpos : B.PositiveOnEdges)
    (hl : B.IsInvProb lam) :
    (Summable fun n : ℕ => ‖densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat) ^ n
        - meanOp (edgeMeasureE B.phat lam)‖)
      ↔ Summable fun n : ℕ => ‖densOp lam B.phat ^ n - meanOp lam‖ := by
  refine (summable_nat_add_iff 1).symm.trans
    (iff_of_eq (congrArg Summable (funext fun n => ?_)))
  exact lifted_beta_succ hpc hpos hl n

/-- **`theo:training_speed`, the lifted mixing sum is `1 + B`** (`cv_divergence.tex:166`, "for DB
is `1+B`"; `theo:db_stable_frozen_full`, `proofs.tex:653`; the sentence at `proofs.tex:589`): when
the backward chain has summable mixing, `B̂₂ = β̂₀ + ∑_{n≥0}β̂_{n+1} = 1 + ∑_{n≥0}β_n`, with
`β̂₀ = ‖I − Π₂‖ = 1` because `E` has two points (`nontrivial_edgeSet`). -/
theorem liftedMixingSum_eq (hpc : G.PathConnected) (hpos : B.PositiveOnEdges)
    (hl : B.IsInvProb lam)
    (hsum : Summable fun n : ℕ => ‖densOp lam B.phat ^ n - meanOp lam‖) :
    liftedMixingSum B lam = 1 + Core.Mixing.B (densOp lam B.phat) (meanOp lam) := by
  haveI := nontrivial_edgeSet B
  obtain ⟨-, -, hp2, htot2⟩ := Graph.edge_setting hpc hpos hl
  have hs2 : Summable (Core.Mixing.beta (densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat))
      (meanOp (edgeMeasureE B.phat lam))) := (lifted_summable_iff hpc hpos hl).mpr hsum
  unfold liftedMixingSum Core.Mixing.B
  rw [hs2.tsum_eq_zero_add, beta_zero_densOp_meanOp hp2 htot2]
  congr 1
  exact tsum_congr fun n => lifted_beta_succ hpc hpos hl n

omit [Fintype V] [DecidableEq V] in
/-- A series of non-negative reals is summable iff its sum in `ℝ≥0∞` is finite. -/
theorem summable_iff_tsum_ofReal_ne_top {f : ℕ → ℝ} (hf : ∀ n, 0 ≤ f n) :
    Summable f ↔ ∑' n, ENNReal.ofReal (f n) ≠ ⊤ :=
  ⟨fun h => h.tsum_ofReal_ne_top, fun h =>
    (ENNReal.summable_toReal h).congr fun n => ENNReal.toReal_ofReal (hf n)⟩

/-- **`theo:training_speed`, "the lifted mixing sum is finite", read literally**: `hsum` of the
principal theorem is `∑_{n≥0}‖P₂ⁿ − Π₂‖ ≠ +∞` in `ℝ≥0∞` — the dual of the reading
`MorozovDB.Leveled.mixing_sum_eq_top` gives "the mixing sum is `+∞`". -/
theorem lifted_summable_iff_ne_top :
    (Summable fun n : ℕ => ‖densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat) ^ n
        - meanOp (edgeMeasureE B.phat lam)‖)
      ↔ ∑' n : ℕ, ENNReal.ofReal ‖densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat) ^ n
          - meanOp (edgeMeasureE B.phat lam)‖ ≠ ⊤ :=
  summable_iff_tsum_ofReal_ne_top fun _ => norm_nonneg _

/-- **`theo:training_speed`, "wherever" is a genuine restriction**: on a leveled — autoregressive
— graph the loop closure is periodic, `‖P^n − Π‖ ≥ 1` for every `n`
(`MorozovDB.Leveled.not_summable_beta`), and so the lifted mixing sum is infinite. -/
theorem lifted_not_summable_of_leveled (L : Graph.Leveled G) (hpc : G.PathConnected)
    (hpos : B.PositiveOnEdges) (hl : B.IsInvProb lam) :
    ¬ Summable fun n : ℕ => ‖densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat) ^ n
        - meanOp (edgeMeasureE B.phat lam)‖ :=
  fun hs => L.not_summable_beta hpc hpos hl ((lifted_summable_iff hpc hpos hl).mp hs)

/-- **`theo:training_speed`, "wherever the lifted mixing sum is finite", made exact**: on the loop
closure of a finite path-connected marked graph, the lifted mixing sum is finite **iff** the
backward chain `π̂_←` is aperiodic at `x₀` (any state) — summable `L²`-mixing is aperiodicity on
these chains (`RemarksA.graphs_vs_L2_aperiodic`, `RemarksA.graphs_vs_L2_periodic`). The DB sentence
therefore carries aperiodicity, as `hsum`, although the state-space clause before it carries none. -/
theorem lifted_summable_iff_aperiodic (hpc : G.PathConnected) (hpos : B.PositiveOnEdges)
    (hl : B.IsInvProb lam) (x₀ : V) :
    (Summable fun n : ℕ => ‖densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat) ^ n
        - meanOp (edgeMeasureE B.phat lam)‖)
      ↔ ¬ ∃ d, RemarksA.PeriodicAt B.phat x₀ d := by
  rw [lifted_summable_iff hpc hpos hl]
  constructor
  · rintro hs ⟨d, hper⟩
    exact (RemarksA.graphs_vs_L2_periodic hpc hpos hl hper).2.2.1 hs
  · intro hap
    exact (RemarksA.graphs_vs_L2_aperiodic hpc hpos hl hap).1.summable

end EdgeLift

/-! ### The sentence -/

section Principal

variable {V : Type*} [Fintype V] [DecidableEq V] {G : Graph.MarkedGraph V}
  {B : Graph.BackwardPolicy G} {lam : V → ℝ}

/-- **`theo:training_speed`, the DB sentence** (`cv_divergence.tex:79–81`): "the DB instance
inherits a local rate through the edge lift wherever the lifted mixing sum is finite (Theorems
`theo:db_stable_frozen` and `theo:local_convergence`)".

On a finite path-connected marked graph with a backward policy positive on the edges of its loop
closure, `λ` the backward chain's invariant probability, `g = (log x)²` and an edge training
measure `ν̂ = wλ₂` with `w ≥ w_min > 0`: if the lifted mixing sum `B̂₂ = ∑_{n≥0}‖P₂ⁿ − Π₂‖` of the
edge chain `K₂` on `E` is finite (`hsum`), then, in the order of the conjuncts,

* the balance loss of `K₂` on `(E, λ₂)` **is** the DB loss (`prop:db_lift`): the DB instance;
* `B̂₂ ≥ 1` and `B̂₂` is a coercivity constant of `K₂` on `L²(λ₂)` (`lem:sigma_mixing`);
* the backward chain's mixing sum `B` is finite and `B̂₂ = 1 + B` (`lem:lift_mixing`);
* the rate `ϱ = g''(1)w_min/B̂₂²` is `2w_min/B̂₂²`, and positive;
* `theo:db_stable_frozen` for the DB loss at `B̂₂`: the linearized descent with a step
  `0 ≤ ε ≤ (4g''(1)‖w‖_{L^∞})^{−1}` conserves `Π₂h` and contracts `‖h − Π₂h‖` by `1 − εϱ` per
  step; along the linearized flow `Π₂h` is conserved and `‖h_t − Π₂h_t‖` decays like `e^{−ϱt}`;
* `theo:local_convergence` for the DB loss at `B̂₂`: the whole conclusion of
  `local_convergence_full_DB_paper` at `g = (log x)²`, `a = 1/2` — the constants, and from every
  `‖h₀‖ ≤ ε₀` a unique DB gradient flow converging to a balanced `c_∞λ₂` at rate `ϱ/2`, and a
  well-defined descent contracting by `1 − γϱ/4` below `γ₀`. -/
theorem training_speed_DB_edge_lift (hpc : G.PathConnected) (hpos : B.PositiveOnEdges)
    (hl : B.IsInvProb lam) {w : EdgeSet B.phat → ℝ} {wmin : ℝ}
    (hwmin0 : 0 < wmin) (hwmin : ∀ e, wmin ≤ w e)
    (hsum : Summable fun n : ℕ => ‖densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat) ^ n
      - meanOp (edgeMeasureE B.phat lam)‖) :
    -- the balance loss of `K₂` on `(E, λ₂)` is the DB loss
    (∀ u : EdgeSet B.phat → ℝ, (∀ e, 0 ≤ u e) →
      loss (edgeKernelE B.phat) (edgeMeasureE B.phat lam)
          (fun z => edgeMeasureE B.phat lam z * w z) u logSq
        = ∑ e : EdgeSet B.phat, edgeMeasureE B.phat lam e * w e
            * logSq (marg₁ (extE B.phat lam u) e.1.2 * B.phat e.1.2 e.1.1
              / (marg₁ (extE B.phat lam u) e.1.1 * disint (extE B.phat lam u) e.1.1 e.1.2)))
    -- `B̂₂ ≥ 1` is a coercivity constant of `K₂` on `L²(λ₂)`
    ∧ 1 ≤ liftedMixingSum B lam
    ∧ (∀ f : EdgeSet B.phat → ℝ,
        Graph.nrmL2 (edgeMeasureE B.phat lam) (perpL2 (edgeMeasureE B.phat lam) f)
          ≤ liftedMixingSum B lam
            * Graph.nrmL2 (edgeMeasureE B.phat lam)
                (Aop (edgeKernelE B.phat) (edgeMeasureE B.phat lam) f))
    -- `B̂₂ = 1 + B`, the backward chain's own mixing sum being finite
    ∧ (Summable fun n : ℕ => ‖densOp lam B.phat ^ n - meanOp lam‖)
    ∧ liftedMixingSum B lam = 1 + Core.Mixing.B (densOp lam B.phat) (meanOp lam)
    -- the rate `ϱ = g''(1)w_min/B̂₂² = 2w_min/B̂₂² > 0`
    ∧ rhoL (deriv (deriv logSq) 1) wmin (liftedMixingSum B lam)
        = 2 * wmin / liftedMixingSum B lam ^ 2
    ∧ 0 < rhoL (deriv (deriv logSq) 1) wmin (liftedMixingSum B lam)
    -- `theo:db_stable_frozen`: the linearized DB descent, below the printed step cap
    ∧ (∀ (eps : ℝ) (h : ℕ → EdgeSet B.phat → ℝ), 0 ≤ eps →
        eps ≤ (4 * deriv (deriv logSq) 1 * supAbsOf w)⁻¹ →
        (∀ k e, h (k + 1) e = h k e - eps * linHess (edgeKernelE B.phat)
          (edgeMeasureE B.phat lam) w (deriv (deriv logSq) 1) (h k) e) →
        (∀ k, Graph.meanL2 (edgeMeasureE B.phat lam) (h k)
            = Graph.meanL2 (edgeMeasureE B.phat lam) (h 0))
        ∧ ∀ k, Graph.nrmL2 (edgeMeasureE B.phat lam) (perpL2 (edgeMeasureE B.phat lam) (h k))
            ≤ (1 - eps * rhoL (deriv (deriv logSq) 1) wmin (liftedMixingSum B lam)) ^ k
              * Graph.nrmL2 (edgeMeasureE B.phat lam) (perpL2 (edgeMeasureE B.phat lam) (h 0)))
    -- `theo:db_stable_frozen`: the linearized DB flow
    ∧ (∀ h : ℝ → EdgeSet B.phat → ℝ,
        (∀ t : ℝ, HasDerivAt h (fun e => -(linHess (edgeKernelE B.phat)
          (edgeMeasureE B.phat lam) w (deriv (deriv logSq) 1) (h t) e)) t) →
        (∀ t : ℝ, Graph.meanL2 (edgeMeasureE B.phat lam) (h t)
            = Graph.meanL2 (edgeMeasureE B.phat lam) (h 0))
        ∧ ∀ t : ℝ, 0 ≤ t →
          Graph.nrmL2 (edgeMeasureE B.phat lam) (perpL2 (edgeMeasureE B.phat lam) (h t))
            ≤ Real.exp (-(rhoL (deriv (deriv logSq) 1) wmin (liftedMixingSum B lam) * t))
              * Graph.nrmL2 (edgeMeasureE B.phat lam) (perpL2 (edgeMeasureE B.phat lam) (h 0)))
    -- `theo:local_convergence`: `local_convergence_full_DB_paper` at `B̂ = B̂₂`, `g = (log x)²`,
    -- `a = 1/2` — the constants, then the nonlinear DB flow and descent
    ∧ ((∃ e, edgeMeasureE B.phat lam e = lamMinOf (edgeMeasureE B.phat lam))
        ∧ (∀ e, lamMinOf (edgeMeasureE B.phat lam) ≤ edgeMeasureE B.phat lam e)
        ∧ 1 ≤ Cinf (lamMinOf (edgeMeasureE B.phat lam)))
    ∧ (eps0W logSq (1 / 2) wmin (supAbsOf w) (liftedMixingSum B lam)
          (lamMinOf (edgeMeasureE B.phat lam))
          ∈ Set.Ioc 0 (1 / 2 / (16 * Cinf (lamMinOf (edgeMeasureE B.phat lam))))
        ∧ 1 ≤ CW logSq (1 / 2) wmin (supAbsOf w)
        ∧ 0 < gamma0W logSq (1 / 2) wmin (supAbsOf w) (liftedMixingSum B lam))
    ∧ ∀ h0 : EdgeSet B.phat → ℝ, Graph.nrmL2 (edgeMeasureE B.phat lam) h0
          ≤ eps0W logSq (1 / 2) wmin (supAbsOf w) (liftedMixingSum B lam)
              (lamMinOf (edgeMeasureE B.phat lam)) →
      (∃ h : ℝ → EdgeSet B.phat → ℝ, h 0 = h0
        ∧ IsGradientFlow (edgeKernelE B.phat) (edgeMeasureE B.phat lam)
            (fun z => edgeMeasureE B.phat lam z * w z) logSqDeriv (fun s x => 1 + h s x)
        ∧ (∀ t : ℝ, 0 ≤ t → ∀ d : EdgeSet B.phat → ℝ,
            HasDerivAt
              (fun s : ℝ => loss (edgeKernelE B.phat) (edgeMeasureE B.phat lam)
                (fun z => edgeMeasureE B.phat lam z * w z) (fun x => 1 + h t x + s * d x) logSq)
              (Graph.ipL2 (edgeMeasureE B.phat lam) (lossGrad (edgeKernelE B.phat)
                (edgeMeasureE B.phat lam) (fun z => edgeMeasureE B.phat lam z * w z) logSqDeriv
                fun z => 1 + h t z) d) 0)
        ∧ (∀ t : ℝ, 0 ≤ t → ∀ x, 0 < 1 + h t x
            ∧ |ratio (edgeKernelE B.phat) (edgeMeasureE B.phat lam) (fun z => 1 + h t z) x - 1|
                ≤ 2 * (1 / 2) / 3)
        ∧ (∀ h' : ℝ → EdgeSet B.phat → ℝ, h' 0 = h0 →
            IsGradientFlow (edgeKernelE B.phat) (edgeMeasureE B.phat lam)
              (fun z => edgeMeasureE B.phat lam z * w z) logSqDeriv (fun s x => 1 + h' s x) →
            ∀ t : ℝ, 0 ≤ t → h' t = h t)
        ∧ ∃ cinf : ℝ, Balanced (edgeKernelE B.phat) (edgeMeasureE B.phat lam) (fun _ => cinf)
            ∧ |cinf - 1 - Graph.meanL2 (edgeMeasureE B.phat lam) h0|
                ≤ CW logSq (1 / 2) wmin (supAbsOf w)
                    * Graph.nrmL2 (edgeMeasureE B.phat lam)
                        (perpL2 (edgeMeasureE B.phat lam) h0) ^ 2
            ∧ (∀ t : ℝ, 0 ≤ t
                → Graph.nrmL2 (edgeMeasureE B.phat lam) (fun x => h t x - (cinf - 1))
                  ≤ 2 * Real.exp (-(rhoL (deriv (deriv logSq) 1) wmin (liftedMixingSum B lam)
                      * t / 2))
                    * Graph.nrmL2 (edgeMeasureE B.phat lam) (perpL2 (edgeMeasureE B.phat lam) h0))
            ∧ Tendsto (fun t => Graph.nrmL2 (edgeMeasureE B.phat lam)
                (fun x => h t x - (cinf - 1))) atTop (𝓝 0))
      ∧ ∀ gam : ℝ, 0 < gam
        → gam ≤ gamma0W logSq (1 / 2) wmin (supAbsOf w) (liftedMixingSum B lam) →
        ∀ hk : ℕ → EdgeSet B.phat → ℝ, hk 0 = h0 →
        (∀ k : ℕ, hk (k + 1) = fun x =>
          hk k x - gam * lossGrad (edgeKernelE B.phat) (edgeMeasureE B.phat lam)
            (fun z => edgeMeasureE B.phat lam z * w z) logSqDeriv (fun z => 1 + hk k z) x) →
        ∀ k : ℕ, ((∀ x, 0 < 1 + hk k x)
          ∧ (∀ x, |ratio (edgeKernelE B.phat) (edgeMeasureE B.phat lam)
              (fun z => 1 + hk k z) x - 1| ≤ 2 * (1 / 2) / 3)
          ∧ ∀ d : EdgeSet B.phat → ℝ,
              HasDerivAt
                (fun t : ℝ => loss (edgeKernelE B.phat) (edgeMeasureE B.phat lam)
                  (fun z => edgeMeasureE B.phat lam z * w z) (fun x => 1 + hk k x + t * d x)
                  logSq)
                (Graph.ipL2 (edgeMeasureE B.phat lam) (lossGrad (edgeKernelE B.phat)
                  (edgeMeasureE B.phat lam) (fun z => edgeMeasureE B.phat lam z * w z) logSqDeriv
                  fun z => 1 + hk k z) d) 0)
          ∧ Graph.nrmL2 (edgeMeasureE B.phat lam) (perpL2 (edgeMeasureE B.phat lam) (hk (k + 1)))
              ≤ (1 - gam * rhoL (deriv (deriv logSq) 1) wmin (liftedMixingSum B lam) / 4)
                  * Graph.nrmL2 (edgeMeasureE B.phat lam)
                      (perpL2 (edgeMeasureE B.phat lam) (hk k)) := by
  haveI := nontrivial_edgeSet B
  obtain ⟨hK2, hinv2, hp2, htot2⟩ := Graph.edge_setting hpc hpos hl
  have hmx : Core.Mixing (densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat))
      (meanOp (edgeMeasureE B.phat lam)) :=
    (mixing_densOp_iff_summable (hK2.toIsMarkovOn _) hinv2 hp2).mpr hsum
  have hB1 : 1 ≤ liftedMixingSum B lam := one_le_B_densOp hp2 hmx
  have hBpos : 0 < liftedMixingSum B lam := lt_of_lt_of_le one_pos hB1
  have hcoer : ∀ f : EdgeSet B.phat → ℝ,
      Graph.nrmL2 (edgeMeasureE B.phat lam) (perpL2 (edgeMeasureE B.phat lam) f)
        ≤ liftedMixingSum B lam
          * Graph.nrmL2 (edgeMeasureE B.phat lam)
              (Aop (edgeKernelE B.phat) (edgeMeasureE B.phat lam) f) :=
    mixing_coercivity_finite hinv2 hp2 hmx
  have hsum1 : Summable fun n : ℕ => ‖densOp lam B.phat ^ n - meanOp lam‖ :=
    (lifted_summable_iff hpc hpos hl).mp hsum
  obtain ⟨hC3, hgd, hg1, hg2⟩ := logSq_C3On_bundle
  have hwsup : ∀ e, w e ≤ supAbsOf w := fun e => (le_abs_self _).trans (abs_le_supAbsOf w e)
  have hws : wmin ≤ supAbsOf w := (hwmin _).trans (hwsup (Graph.wrapEdge B))
  have hwsup0 : 0 ≤ supAbsOf w := hwmin0.le.trans hws
  refine ⟨fun u hu => loss_edgeE_eq_db B.phat_nonneg hl.nonneg hu _ logSq, hB1, hcoer, hsum1,
    liftedMixingSum_eq hpc hpos hl hsum1, by rw [rhoL, logSq_deriv2_one],
    rhoL_pos (mul_pos hg2 hwmin0) hBpos, fun eps h heps hcap hstep => ?_,
    fun h hflow => stable_frozen_decay_finite hinv2 hK2.nonneg hp2 htot2 hg2.le hwmin0.le hwmin
      hBpos hcoer hflow, ?_⟩
  · have hX : 0 < 4 * deriv (deriv logSq) 1 * supAbsOf w :=
      mul_pos (mul_pos four_pos hg2) (hwmin0.trans_le hws)
    have hepsL : eps * (4 * deriv (deriv logSq) 1 * supAbsOf w) ≤ 1 :=
      calc eps * (4 * deriv (deriv logSq) 1 * supAbsOf w)
          ≤ (4 * deriv (deriv logSq) 1 * supAbsOf w)⁻¹
              * (4 * deriv (deriv logSq) 1 * supAbsOf w) :=
            mul_le_mul_of_nonneg_right hcap hX.le
        _ = 1 := inv_mul_cancel₀ hX.ne'
    exact stable_frozen_discrete_finite hK2 hinv2 hp2 htot2 hg2.le hwmin0.le hwmin hwsup hwsup0
      hBpos hcoer heps hepsL (Graph.hrho_of_step hB1 hg2.le hwmin0.le hws heps hepsL) hstep
  · exact local_convergence_full_DB_paper (w := w) (g := logSq) (gd := logSqDeriv) (a := 1 / 2)
      ((Core.phat_isMarkov B).toIsMarkovOn lam) (Core.isInvariant_of_isInvProb B hl)
      (hl.pos hpc hpos) hl.total (by norm_num) hC3 hgd hg1 hg2 hwmin0 hwmin hB1 hcoer

end Principal

/-! ### Neither the hypotheses nor the conclusions are empty (kb 0025, 0027) -/

section Witness

variable {V : Type*} [Fintype V] [DecidableEq V] {G : Graph.MarkedGraph V}
  {B : Graph.BackwardPolicy G} {lam : V → ℝ}

/-- The indicator `𝟙_{(s_f,s₀)}` of the wrap pair, on `E`. -/
noncomputable def wrapInd (B : Graph.BackwardPolicy G) : EdgeSet B.phat → ℝ :=
  fun e => if e = Graph.wrapEdge B then 1 else 0

/-- `𝟙_{(s_f,s₀)}` is not constant on `E`, which has another pair (`nontrivial_edgeSet`). -/
theorem wrapInd_ne_const (B : Graph.BackwardPolicy G) (c : ℝ) : wrapInd B ≠ fun _ => c := by
  intro h
  haveI := nontrivial_edgeSet B
  obtain ⟨e, he⟩ := exists_ne (Graph.wrapEdge B)
  have h1 := congrFun h (Graph.wrapEdge B)
  have h2 := congrFun h e
  simp only [wrapInd, if_true, if_neg he] at h1 h2
  linarith

/-- Under summable lifted mixing a balanced density on `E` is constant: `μK₂ = μ` makes it a
fixed point of the density action, and summable mixing is ergodicity
(`LocalConvergenceMixing.eq_const_of_densAct_eq`). -/
theorem eq_const_of_balanced_edge (hpc : G.PathConnected) (hpos : B.PositiveOnEdges)
    (hl : B.IsInvProb lam)
    (hsum : Summable fun n : ℕ => ‖densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat) ^ n
      - meanOp (edgeMeasureE B.phat lam)‖)
    {u : EdgeSet B.phat → ℝ} (hu : Balanced (edgeKernelE B.phat) (edgeMeasureE B.phat lam) u) :
    u = fun _ => Graph.meanL2 (edgeMeasureE B.phat lam) u := by
  obtain ⟨hK2, hinv2, hp2, -⟩ := Graph.edge_setting hpc hpos hl
  have hmx := (mixing_densOp_iff_summable (hK2.toIsMarkovOn _) hinv2 hp2).mpr hsum
  refine eq_const_of_densAct_eq hp2 hmx (funext fun y => ?_)
  have hy := hu y
  simp only [pushMass] at hy
  rw [Core.densAct_apply, Finset.sum_congr rfl fun x _ => mul_right_comm
    (edgeMeasureE B.phat lam x) (edgeKernelE B.phat x y) (u x), hy]
  exact mul_div_cancel_left₀ (u y) (hp2 y).ne'

/-- A function of zero `L²(μ)`-norm vanishes, for a positive weight `μ`. -/
theorem eq_zero_of_nrmL2_eq_zero {W : Type*} [Fintype W] {mu f : W → ℝ} (hmu : ∀ x, 0 < mu x)
    (hf : Graph.nrmL2 mu f = 0) : f = fun _ => 0 := by
  have h0 : wtL2 mu f = 0 := by
    rw [← norm_eq_zero, norm_wtL2 fun x => (hmu x).le]
    exact hf
  exact wtL2_injective hmu (h0.trans (wtL2_zero mu).symm)

/-- **`theo:training_speed`, the DB sentence is not vacuous on any instance** (kb 0025, 0027):
whenever `training_speed_DB_edge_lift` applies,

* its linearized clauses are exercised off the balanced ray: `𝟙_{(s_f,s₀)}` has a deviation from
  its mean of positive norm, the step cap `(4g''(1)‖w‖_{L^∞})^{−1}` is positive, and the
  linearized descent (at any step) and the linearized flow run from `𝟙_{(s_f,s₀)}`
  (`Graph.linDescent`, `Graph.exists_linFlow`);
* its nonlinear clause is exercised off balance: from `ε₀𝟙_{(s_f,s₀)}`, inside the paper's ball,
  the DB gradient flow exists, is **not** balanced at `t = 0`, and converges to a balanced flow. -/
theorem training_speed_DB_edge_lift_nonvacuous (hpc : G.PathConnected)
    (hpos : B.PositiveOnEdges) (hl : B.IsInvProb lam) {w : EdgeSet B.phat → ℝ} {wmin : ℝ}
    (hwmin0 : 0 < wmin) (hwmin : ∀ e, wmin ≤ w e)
    (hsum : Summable fun n : ℕ => ‖densOp (edgeMeasureE B.phat lam) (edgeKernelE B.phat) ^ n
      - meanOp (edgeMeasureE B.phat lam)‖) :
    0 < Graph.nrmL2 (edgeMeasureE B.phat lam) (perpL2 (edgeMeasureE B.phat lam) (wrapInd B))
    ∧ 0 < (4 * deriv (deriv logSq) 1 * supAbsOf w)⁻¹
    ∧ (∀ eps : ℝ, ∃ h : ℕ → EdgeSet B.phat → ℝ, h 0 = wrapInd B
        ∧ ∀ k e, h (k + 1) e = h k e - eps * linHess (edgeKernelE B.phat)
          (edgeMeasureE B.phat lam) w (deriv (deriv logSq) 1) (h k) e)
    ∧ (∃ h : ℝ → EdgeSet B.phat → ℝ, h 0 = wrapInd B
        ∧ ∀ t : ℝ, HasDerivAt h (fun e => -(linHess (edgeKernelE B.phat)
          (edgeMeasureE B.phat lam) w (deriv (deriv logSq) 1) (h t) e)) t)
    ∧ ∃ h : ℝ → EdgeSet B.phat → ℝ,
        IsGradientFlow (edgeKernelE B.phat) (edgeMeasureE B.phat lam)
            (fun z => edgeMeasureE B.phat lam z * w z) logSqDeriv (fun s e => 1 + h s e)
        ∧ ¬ Balanced (edgeKernelE B.phat) (edgeMeasureE B.phat lam) (fun e => 1 + h 0 e)
        ∧ ∃ cinf : ℝ, Balanced (edgeKernelE B.phat) (edgeMeasureE B.phat lam) (fun _ => cinf)
            ∧ Tendsto (fun t => Graph.nrmL2 (edgeMeasureE B.phat lam)
                (fun e => h t e - (cinf - 1))) atTop (𝓝 0) := by
  obtain ⟨-, -, hp2, htot2⟩ := Graph.edge_setting hpc hpos hl
  obtain ⟨-, -, -, -, -, -, -, -, -, -, ⟨hc, -, -⟩, hmain⟩ :=
    training_speed_DB_edge_lift hpc hpos hl hwmin0 hwmin hsum
  obtain ⟨-, -, -, hg2⟩ := logSq_C3On_bundle
  have hws : wmin ≤ supAbsOf w :=
    (hwmin _).trans ((le_abs_self _).trans (abs_le_supAbsOf w (Graph.wrapEdge B)))
  set ε := eps0W logSq (1 / 2) wmin (supAbsOf w) (liftedMixingSum B lam)
    (lamMinOf (edgeMeasureE B.phat lam)) with hεdef
  have hε : 0 < ε := hc.1
  refine ⟨?_, inv_pos.mpr (mul_pos (mul_pos four_pos hg2) (hwmin0.trans_le hws)),
    fun eps => ⟨Graph.linDescent _ _ w _ eps (wrapInd B), rfl, Graph.linDescent_step _ _ _ _ _ _⟩,
    Graph.exists_linFlow _ _ w _ (wrapInd B), ?_⟩
  · refine lt_of_le_of_ne (Graph.nrmL2_nonneg _ _) fun h0 => ?_
    have hz := eq_zero_of_nrmL2_eq_zero hp2 h0.symm
    refine wrapInd_ne_const B (Graph.meanL2 (edgeMeasureE B.phat lam) (wrapInd B))
      (funext fun e => ?_)
    have := congrFun hz e
    rw [perpL2_apply] at this
    linarith
  · have hip : Graph.ipL2 (edgeMeasureE B.phat lam) (wrapInd B) (wrapInd B) ≤ 1 := by
      calc Graph.ipL2 (edgeMeasureE B.phat lam) (wrapInd B) (wrapInd B)
          ≤ ∑ e, edgeMeasureE B.phat lam e := by
            refine Finset.sum_le_sum fun e _ => ?_
            have hle : wrapInd B e * wrapInd B e ≤ 1 := by
              unfold wrapInd; split_ifs <;> norm_num
            nlinarith [hp2 e]
        _ = 1 := htot2
    have hind : Graph.nrmL2 (edgeMeasureE B.phat lam) (wrapInd B) ≤ 1 := by
      rw [Graph.nrmL2, Real.sqrt_le_one]
      exact hip
    have hnorm0 : Graph.nrmL2 (edgeMeasureE B.phat lam) (fun e => ε * wrapInd B e) ≤ ε := by
      rw [nrmL2_smul, abs_of_pos hε]
      nlinarith [Graph.nrmL2_nonneg (edgeMeasureE B.phat lam) (wrapInd B)]
    obtain ⟨⟨h, hh0, hflow, -, -, -, cinf, hbal, -, -, hlim⟩, -⟩ := hmain _ hnorm0
    refine ⟨h, hflow, fun hb => ?_, cinf, hbal, hlim⟩
    have hconst := eq_const_of_balanced_edge hpc hpos hl hsum hb
    rw [hh0] at hconst
    set m := Graph.meanL2 (edgeMeasureE B.phat lam) (fun e => 1 + ε * wrapInd B e)
    refine wrapInd_ne_const B ((m - 1) / ε) (funext fun e => ?_)
    have := congrFun hconst e
    field_simp
    linarith

/-- **`theo:training_speed`, the DB sentence, inhabited** (kb 0025): on the aperiodic triangle
`s₀ → x → s_f`, `s₀ → s_f` of `RemarksA` (returns to `s₀` of lengths `2` and `3`), with its
invariant probability and `w ≡ 1`, the lifted mixing sum is finite — from the backward chain's
summable mixing (`RemarksA.graphs_vs_L2_aperiodic`) through `lifted_summable_iff` — and equals
`1 + B`; the linearized start `𝟙_{(s_f,s₀)}` is off the balanced ray; and the DB gradient flow of
`training_speed_DB_edge_lift` runs from a non-balanced start to a balanced flow. -/
theorem triangle_DB_edge_lift_check :
    ∃ lam : Fin 3 → ℝ, RemarksA.triPolicy.IsInvProb lam
      ∧ (Summable fun n : ℕ =>
          ‖densOp (edgeMeasureE RemarksA.triPolicy.phat lam)
              (edgeKernelE RemarksA.triPolicy.phat) ^ n
            - meanOp (edgeMeasureE RemarksA.triPolicy.phat lam)‖)
      ∧ liftedMixingSum RemarksA.triPolicy lam
          = 1 + Core.Mixing.B (densOp lam RemarksA.triPolicy.phat) (meanOp lam)
      ∧ 0 < Graph.nrmL2 (edgeMeasureE RemarksA.triPolicy.phat lam)
          (perpL2 (edgeMeasureE RemarksA.triPolicy.phat lam) (wrapInd RemarksA.triPolicy))
      ∧ ∃ h : ℝ → EdgeSet RemarksA.triPolicy.phat → ℝ,
          IsGradientFlow (edgeKernelE RemarksA.triPolicy.phat)
              (edgeMeasureE RemarksA.triPolicy.phat lam)
              (fun z => edgeMeasureE RemarksA.triPolicy.phat lam z * 1) logSqDeriv
              (fun s e => 1 + h s e)
          ∧ ¬ Balanced (edgeKernelE RemarksA.triPolicy.phat)
              (edgeMeasureE RemarksA.triPolicy.phat lam) (fun e => 1 + h 0 e)
          ∧ ∃ cinf : ℝ, Balanced (edgeKernelE RemarksA.triPolicy.phat)
              (edgeMeasureE RemarksA.triPolicy.phat lam) (fun _ => cinf)
            ∧ Tendsto (fun t => Graph.nrmL2 (edgeMeasureE RemarksA.triPolicy.phat lam)
                (fun e => h t e - (cinf - 1))) atTop (𝓝 0) := by
  obtain ⟨lam, hl⟩ := RemarksA.triPolicy.exists_invProb
  obtain ⟨hmx, -, -⟩ := RemarksA.graphs_vs_L2_aperiodic RemarksA.triGraph_pathConnected
    RemarksA.triPolicy_positiveOnEdges hl RemarksA.triPolicy_aperiodic
  have hsum := (lifted_summable_iff RemarksA.triGraph_pathConnected
    RemarksA.triPolicy_positiveOnEdges hl).mpr hmx.summable
  obtain ⟨-, -, -, -, heq, -⟩ := training_speed_DB_edge_lift (w := fun _ => (1 : ℝ))
    RemarksA.triGraph_pathConnected RemarksA.triPolicy_positiveOnEdges hl one_pos
    (fun _ => le_rfl) hsum
  obtain ⟨hperp, -, -, -, hrest⟩ := training_speed_DB_edge_lift_nonvacuous
    (w := fun _ => (1 : ℝ)) RemarksA.triGraph_pathConnected RemarksA.triPolicy_positiveOnEdges hl
    one_pos (fun _ => le_rfl) hsum
  exact ⟨lam, hl, hsum, heq, hperp, hrest⟩

/-- **`theo:training_speed`, "wherever" on an instance**: on the autoregressive graph `s₀ → s_f`
(`MorozovConsume.ar`, leveled, its loop closure the swap, of period `2`) the lifted mixing sum is
infinite, so the DB sentence says nothing there; the DB rate on that graph is
`prop:morozov_rate`*(3)*'s, at `1 + B̂_σ` (`MorozovDB.ar_local_convergence_DB_witness`). -/
theorem ar_lifted_not_summable :
    ¬ Summable fun n : ℕ => ‖densOp (edgeMeasureE Graph.arPol.phat Graph.arLam)
        (edgeKernelE Graph.arPol.phat) ^ n - meanOp (edgeMeasureE Graph.arPol.phat Graph.arLam)‖ :=
  lifted_not_summable_of_leveled Graph.arLeveled Graph.arPathConnected Graph.arPositiveOnEdges
    Graph.arIsInvProb

end Witness

end GFNBounds.Balance.TrainingSpeedDB
