#!/usr/bin/env python3
"""Render `docs/COVERAGE.md`: every statement the library is chartered to cover, and where each
one stands. Multi-source since 2026-09-08 — Appendices A (`proofs.tex`), B
(`silva_comparison.tex`) and H (`app_doubling.tex`); rows are grouped by appendix."""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

MARK = {"closed": "✅ closed", "partial": "🟡 partial", "open": "⬜ open", "stale": "⚠️ STALE"}

m = json.load(open(os.path.join(ROOT, "paper-map.json"), encoding="utf-8"))
sorries = json.load(open(os.path.join(ROOT, "docs", "sorry.json"), encoding="utf-8"))
by_label = {}
for s in sorries:
    by_label.setdefault(s["label"], []).append(s["id"])

SRC = {"proofs.tex": "A", "silva_comparison.tex": "B", "app_doubling.tex": "H"}

rows, counts = [], {"closed": 0, "partial": 0, "open": 0, "stale": 0}
for st in m["statements"]:
    counts[st["status"]] = counts.get(st["status"], 0) + 1
    files = "<br>".join("`%s`" % f.replace("GFNBounds/", "")
                                     .replace("scaffold/GFNBoundsScaffold/", "scaffold:")
                        for f in st["lean_files"]) or "—"
    rows.append("| %s | `%s` | %d–%d | %s | %s | %s | %s |" % (
        SRC.get(st.get("source", "app_doubling.tex"), "?"),
        st["label"], st["tex_span"][0], st["tex_span"][1],
        MARK.get(st["status"], st["status"]), st["bucket"] or "—", files,
        ", ".join("`%s`" % i for i in by_label.get(st["label"], [])) or "—"))

with open(os.path.join(ROOT, "docs", "COVERAGE.md"), "w", encoding="utf-8") as fh:
    fh.write("# Coverage of Appendices A, B and H\n\n"
             "Generated by `scripts/coverage.py`; do not edit by hand.\n\n")
    fh.write("Sources, at paper commit `%s`: %s.\n\n"
             % (m["paper"]["git_commit"],
                ", ".join("**%s** `%s`" % (v["appendix"], k)
                          for k, v in sorted(m.get("sources", {}).items(),
                                             key=lambda kv: kv[1]["appendix"]))))
    fh.write("**%d closed · %d partial · %d open · %d stale**, of %d statements.\n\n"
             % (counts.get("closed", 0), counts.get("partial", 0), counts.get("open", 0),
                counts.get("stale", 0), len(m["statements"])))
    fh.write("`partial` means some items of a multi-part statement are proved and others are not; "
             "the `scope_notes` field of `paper-map.json` says which.\n\n")
    fh.write("The **bucket** says how far the rest is, and every non-`A` row carries its "
             "obstruction in `scope_notes`:\n\n"
             "| bucket | meaning |\n|---|---|\n"
             "| `A` | nothing left; the statement is certified in full |\n"
             "| `B` | what remains is routine on the layers already built |\n"
             "| `C` | **hard** — attempted and blocked on a named obstruction |\n"
             "| `D` | deferred — needs a layer this library has not built, or is flagged "
             "unproved in the paper itself |\n\n")
    fh.write("| app | paper label | tex lines | status | bucket | Lean | open sorries |\n")
    fh.write("|---|---|---|---|---|---|---|\n")
    fh.write("\n".join(rows) + "\n")
print("coverage: %d closed, %d partial, %d open"
      % (counts.get("closed", 0), counts.get("partial", 0), counts.get("open", 0)))
