#!/usr/bin/env python3
"""Render `docs/COVERAGE.md`: the 41 statements of Appendix H and where each one stands."""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

MARK = {"closed": "✅ closed", "partial": "🟡 partial", "open": "⬜ open", "stale": "⚠️ STALE"}

m = json.load(open(os.path.join(ROOT, "paper-map.json"), encoding="utf-8"))
sorries = json.load(open(os.path.join(ROOT, "docs", "sorry.json"), encoding="utf-8"))
by_label = {}
for s in sorries:
    by_label.setdefault(s["label"], []).append(s["id"])

rows, counts = [], {"closed": 0, "partial": 0, "open": 0, "stale": 0}
for st in m["statements"]:
    counts[st["status"]] = counts.get(st["status"], 0) + 1
    files = "<br>".join("`%s`" % f.replace("GFNBounds/Doubling/", "")
                                     .replace("scaffold/GFNBoundsScaffold/Doubling/", "scaffold:")
                        for f in st["lean_files"]) or "—"
    rows.append("| `%s` | %d–%d | %s | %s | %s | %s |" % (
        st["label"], st["tex_span"][0], st["tex_span"][1],
        MARK.get(st["status"], st["status"]), st["bucket"] or "—", files,
        ", ".join("`%s`" % i for i in by_label.get(st["label"], [])) or "—"))

with open(os.path.join(ROOT, "docs", "COVERAGE.md"), "w", encoding="utf-8") as fh:
    fh.write("# Coverage of Appendix H\n\nGenerated by `scripts/coverage.py`; do not edit by hand.\n\n")
    fh.write("Source: `%s` at commit `%s`.\n\n" % (m["paper"]["path"], m["paper"]["git_commit"]))
    fh.write("**%d closed · %d partial · %d open · %d stale**, of %d statements.\n\n"
             % (counts.get("closed", 0), counts.get("partial", 0), counts.get("open", 0),
                counts.get("stale", 0), len(m["statements"])))
    fh.write("`partial` means some items of a multi-part statement are proved and others are not; "
             "the `scope_notes` field of `paper-map.json` says which.\n\n")
    fh.write("| paper label | tex lines | status | bucket | Lean | open sorries |\n")
    fh.write("|---|---|---|---|---|---|\n")
    fh.write("\n".join(rows) + "\n")
print("coverage: %d closed, %d partial, %d open"
      % (counts.get("closed", 0), counts.get("partial", 0), counts.get("open", 0)))
