#!/usr/bin/env python3
"""Build `dashboard/` — the static site node1 serves.

Nothing here is a source of truth. Every number is read from an artefact another script
already wrote (`paper-map.json`, `docs/sorry.json`, `docs/repo-map.json`, `build.log`), so the
dashboard cannot disagree with `make check`; if it looks stale, the fix is to re-run the gate,
not to edit this file.

Layout of the output:

    dashboard/
      index.html          the landing page — headline, per-appendix progress, the links
      dashboard.css       one stylesheet, light and dark, shared by every page here
      coverage.html       docs/COVERAGE.md, rendered
      sorry-status.html   docs/SORRY-STATUS.md, rendered
      repo-map.html       docs/REPO-MAP.md, rendered
      repo-index.html     docs/REPO-INDEX.md, rendered
      readme.html         README.md, rendered
      lean-graph.svg      the verified dependency graph, from proof terms
      print.pdf           the blueprint, as a paper
      blueprint/          leanblueprint's own web output, verbatim
      status.json         the machine twin of the headline numbers

Markdown is rendered by pandoc into a fragment and wrapped in the local template, so the
generated docs and the landing page look like one site. `make dashboard` builds it;
`make deploy` ships it.
"""
import json, os, shutil, subprocess, sys, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dashboard")

# The skill's fixed status palette: never themed, and never reused for a series. `open` is not a
# failure state, so it takes the neutral track rather than `critical`; `stale` is the only red.
STATUS = {
    "closed":  ("Closed",  "\u2705", "var(--status-good)"),
    "partial": ("Partial", "\U0001f7e1", "var(--status-warning)"),
    "open":    ("Open",    "\u2b1c", "var(--track)"),
    "stale":   ("Stale",   "\u26a0\ufe0f", "var(--status-critical)"),
}
ORDER = ["closed", "partial", "open", "stale"]


def sh(*cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def git(*args, cwd=ROOT):
    r = sh("git", "-C", cwd, *args)
    return r.stdout.strip() if r.returncode == 0 else "?"


def read_json(*parts, default=None):
    p = os.path.join(ROOT, *parts)
    if not os.path.exists(p):
        return default
    with open(p, encoding="utf-8") as fh:
        return json.load(fh)


# ---------------------------------------------------------------- the numbers

def collect():
    m = read_json("paper-map.json")
    sorries = read_json("docs", "sorry.json", default=[])
    repomap = read_json("docs", "repo-map.json", default={"files": []})
    app_of = {k: v["appendix"] for k, v in m.get("sources", {}).items()}

    total = {k: 0 for k in ORDER}
    per_app = {}
    for st in m["statements"]:
        app = app_of.get(st.get("source", "app_doubling.tex"), "?")
        per_app.setdefault(app, {k: 0 for k in ORDER})
        per_app[app][st["status"]] = per_app[app].get(st["status"], 0) + 1
        total[st["status"]] = total.get(st["status"], 0) + 1

    files = repomap.get("files", [])
    decls = sum(len(f.get("decls", [])) for f in files)

    # `make check` writes build.log last; its final line tells us whether the build stood up.
    log = os.path.join(ROOT, "build.log")
    built = os.path.exists(log) and "Build completed successfully" in open(
        log, encoding="utf-8", errors="replace").read()[-4000:]

    return {
        "statements": total,
        "n_statements": len(m["statements"]),
        "per_appendix": per_app,
        "appendices": {v["appendix"]: k for k, v in m.get("sources", {}).items()},
        "sorries": len(sorries),
        "files": len(files),
        "decls": decls,
        "library_commit": git("rev-parse", "--short", "HEAD"),
        "library_dirty": git("status", "--porcelain") != "",
        "paper_commit": m["paper"]["git_commit"],
        "build_ok": built,
        "generated": datetime.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M %Z"),
    }


# ---------------------------------------------------------------- the template

CSS = """/* Generated by scripts/dashboard.py. Roles, not raw hex, so the two modes swap in one
   place. Surfaces and ink are the reference palette's; the four status steps are fixed and
   identical in both modes by design. */
:root {
  color-scheme: light;
  --surface-1: #fcfcfb;  --plane: #f9f9f7;
  --ink-1: #0b0b0b;      --ink-2: #52514e;   --ink-muted: #898781;
  --grid: #e1e0d9;       --baseline: #c3c2b7; --track: #e1e0d9;
  --border: rgba(11,11,11,0.10);
  --status-good: #0ca30c; --status-warning: #fab219;
  --status-serious: #ec835a; --status-critical: #d03b3b;
  --link: #2a78d6;
  --sans: system-ui, -apple-system, "Segoe UI", sans-serif;
  --mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
}
@media (prefers-color-scheme: dark) {
  :root:where(:not([data-theme="light"])) {
    color-scheme: dark;
    --surface-1: #1a1a19; --plane: #0d0d0d;
    --ink-1: #ffffff;     --ink-2: #c3c2b7;  --ink-muted: #898781;
    --grid: #2c2c2a;      --baseline: #383835; --track: #2c2c2a;
    --border: rgba(255,255,255,0.10);
    --link: #3987e5;
  }
}
:root[data-theme="dark"] {
  color-scheme: dark;
  --surface-1: #1a1a19; --plane: #0d0d0d;
  --ink-1: #ffffff;     --ink-2: #c3c2b7;  --ink-muted: #898781;
  --grid: #2c2c2a;      --baseline: #383835; --track: #2c2c2a;
  --border: rgba(255,255,255,0.10);
  --link: #3987e5;
}

* { box-sizing: border-box; }
body {
  margin: 0; padding: 0 1.25rem 5rem;
  background: var(--plane); color: var(--ink-1);
  font-family: var(--sans); font-size: 16px; line-height: 1.55;
  -webkit-font-smoothing: antialiased;
}
.wrap { max-width: 62rem; margin: 0 auto; }
a { color: var(--link); text-decoration-thickness: 1px; text-underline-offset: 2px; }

header.masthead { padding: 3rem 0 1.5rem; border-bottom: 1px solid var(--grid); }
.eyebrow { font-size: .8125rem; letter-spacing: .08em; text-transform: uppercase;
           color: var(--ink-muted); margin: 0 0 .5rem; }
h1 { font-size: 1.75rem; font-weight: 650; margin: 0 0 .4rem; letter-spacing: -.01em; }
.masthead p { color: var(--ink-2); margin: 0; max-width: 46rem; }

section { margin: 2.5rem 0 0; }
h2 { font-size: 1.0625rem; font-weight: 650; margin: 0 0 1rem;
     letter-spacing: .01em; color: var(--ink-1); }

/* the one hero figure */
.hero { display: flex; align-items: baseline; gap: 1rem; flex-wrap: wrap;
        margin: 2rem 0 .25rem; }
.hero .figure { font-size: 4rem; font-weight: 650; line-height: 1; letter-spacing: -.03em; }
.hero .caption { color: var(--ink-2); max-width: 30rem; }

.chips { display: flex; gap: .5rem; flex-wrap: wrap; margin: 1rem 0 0; }
#theme { position: fixed; top: .9rem; right: .9rem; z-index: 30;
         border: 1px solid var(--border); background: var(--surface-1); color: var(--ink-2);
         border-radius: 999px; padding: .35rem .8rem; font: inherit; font-size: .8125rem;
         cursor: pointer; }
#theme:hover { border-color: var(--baseline); color: var(--ink-1); }
.chip { display: inline-flex; align-items: center; gap: .4rem;
        border: 1px solid var(--border); background: var(--surface-1);
        border-radius: 999px; padding: .3rem .75rem; font-size: .8125rem; color: var(--ink-2); }
.chip .dot { width: .5rem; height: .5rem; border-radius: 50%; flex: none; }

.tiles { display: grid; gap: .75rem; grid-template-columns: repeat(auto-fit, minmax(9.5rem, 1fr)); }
.tile { background: var(--surface-1); border: 1px solid var(--border);
        border-radius: .5rem; padding: .9rem 1rem; }
.tile .label { font-size: .8125rem; color: var(--ink-2); margin: 0 0 .35rem;
               display: flex; align-items: center; gap: .4rem; }
.tile .value { font-size: 1.875rem; font-weight: 650; line-height: 1.1; }
.tile .sub { font-size: .75rem; color: var(--ink-muted); margin-top: .15rem; }

/* stacked progress — 2px surface gaps do the separating, never a stroke */
.bars { display: grid; gap: .9rem; }
.bar-row { display: grid; grid-template-columns: 8.5rem 1fr; gap: .9rem; align-items: center; }
.bar-row .name { font-size: .875rem; color: var(--ink-2); }
.bar-row .name b { color: var(--ink-1); font-weight: 600; }
.bar { display: flex; height: 2rem; border-radius: 4px; overflow: visible;
       background: transparent; }
.seg { height: 100%; position: relative; display: flex; align-items: center;
       justify-content: center; font-size: .75rem; font-weight: 600;
       box-shadow: 0 0 0 2px var(--plane); cursor: default; }
.seg:first-child { border-radius: 4px 0 0 4px; }
.seg:last-child  { border-radius: 0 4px 4px 0; }
.seg + .seg { margin-left: 2px; }
/* A label inside a fill picks ink or white by the fill's luminance — WCAG contrast on the
   four status steps: ink on good 6.3:1 and on warning 11.4:1, white on critical 4.8:1. The
   track is not a data fill, so its label wears a text token and follows the mode. */
.seg .inlabel { color: #0b0b0b; }
.seg.on-track .inlabel { color: var(--ink-2); }
.seg.on-dark .inlabel { color: #ffffff; }

@media (max-width: 34rem) {
  .bar-row { grid-template-columns: 1fr; gap: .3rem; }
}

/* links index */
.links { display: grid; gap: .75rem; grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr)); }
.card { display: block; background: var(--surface-1); border: 1px solid var(--border);
        border-radius: .5rem; padding: 1rem 1.1rem; text-decoration: none; color: inherit; }
.card:hover { border-color: var(--baseline); }
.card .t { font-weight: 600; color: var(--link); margin-bottom: .2rem; }
.card .d { font-size: .8125rem; color: var(--ink-2); line-height: 1.45; }

table { border-collapse: collapse; width: 100%; font-size: .875rem; }
th, td { text-align: left; padding: .4rem .6rem; border-bottom: 1px solid var(--grid);
         vertical-align: top; }
th { color: var(--ink-2); font-weight: 600; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
details { margin-top: 1rem; }
summary { cursor: pointer; color: var(--ink-2); font-size: .875rem; }
code { font-family: var(--mono); font-size: .875em;
       background: var(--surface-1); border: 1px solid var(--border);
       border-radius: 3px; padding: .05em .3em; }
pre { background: var(--surface-1); border: 1px solid var(--border);
      border-radius: .5rem; padding: .9rem 1rem; overflow-x: auto; }
pre code { background: none; border: 0; padding: 0; }
blockquote { margin: 1rem 0; padding: .25rem 0 .25rem 1rem;
             border-left: 3px solid var(--grid); color: var(--ink-2); }

footer { margin-top: 3.5rem; padding-top: 1.25rem; border-top: 1px solid var(--grid);
         font-size: .8125rem; color: var(--ink-muted); }
footer a { color: var(--ink-2); }

/* the doc pages */
.doc { background: var(--surface-1); border: 1px solid var(--border);
       border-radius: .5rem; padding: 1.5rem 1.75rem; margin-top: 1.5rem; overflow-x: auto; }
.doc h1 { font-size: 1.5rem; }
.doc h2 { font-size: 1.125rem; margin-top: 2rem; }
.doc table { margin: 1rem 0; }
.backlink { display: inline-block; margin-top: 1.5rem; font-size: .875rem; }

#tip { position: fixed; z-index: 40; pointer-events: none; opacity: 0;
       transition: opacity .08s linear; background: var(--surface-1);
       border: 1px solid var(--baseline); border-radius: .375rem;
       padding: .45rem .6rem; font-size: .8125rem; color: var(--ink-1);
       box-shadow: 0 4px 14px rgba(0,0,0,.14); max-width: 18rem; }
#tip .k { color: var(--ink-2); }
"""

THEME_JS = """<button id="theme" type="button" aria-label="Switch colour theme">Theme</button>
<script>
// The stylesheet carries both modes; this only stamps the winning scope on <html>.
(function () {
  var root = document.documentElement, key = 'gfnbounds-theme';
  var saved = null;
  try { saved = localStorage.getItem(key); } catch (e) {}
  if (saved) root.setAttribute('data-theme', saved);
  document.getElementById('theme').addEventListener('click', function () {
    var dark = getComputedStyle(root).colorScheme.indexOf('dark') >= 0;
    var next = dark ? 'light' : 'dark';
    root.setAttribute('data-theme', next);
    try { localStorage.setItem(key, next); } catch (e) {}
  });
})();
</script>"""

TIP_JS = """<div id="tip" role="status" aria-live="polite"></div>
<script>
// Per-mark hover tooltip for the stacked segments. Static page, so no library: the segment
// carries its own text in data-tip and the box follows the pointer.
(function () {
  var tip = document.getElementById('tip');
  if (!tip) return;
  function show(e) {
    var t = e.currentTarget.getAttribute('data-tip');
    if (!t) return;
    tip.innerHTML = t;
    tip.style.opacity = '1';
    move(e);
  }
  function move(e) {
    var pad = 14, w = tip.offsetWidth, h = tip.offsetHeight;
    var x = Math.min(e.clientX + pad, window.innerWidth - w - 8);
    var y = e.clientY - h - pad;
    if (y < 8) y = e.clientY + pad;
    tip.style.left = x + 'px';
    tip.style.top = y + 'px';
  }
  function hide() { tip.style.opacity = '0'; }
  document.querySelectorAll('[data-tip]').forEach(function (el) {
    el.addEventListener('mouseenter', show);
    el.addEventListener('mousemove', move);
    el.addEventListener('mouseleave', hide);
    el.addEventListener('focus', show);
    el.addEventListener('blur', hide);
  });
})();
</script>"""


def page(title, body, css_href="dashboard.css", extra=""):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<link rel="stylesheet" href="{css_href}">
</head>
<body>
<div class="wrap">
{body}
</div>
{extra}
</body>
</html>
"""


# ---------------------------------------------------------------- the landing page

def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def bar(counts, label_html, tip_prefix):
    total = sum(counts.values()) or 1
    segs = []
    for k in ORDER:
        n = counts.get(k, 0)
        if not n:
            continue
        name, icon, color = STATUS[k]
        pct = 100.0 * n / total
        # A label goes inside only when it comfortably fits; otherwise the legend and the
        # tooltip carry it. Never clipped.
        inner = f'<span class="inlabel">{n}</span>' if pct >= 9 else ""
        dark = " on-dark" if k == "stale" else (" on-track" if k == "open" else "")
        tip = (f'<b>{esc(name)}</b> &middot; {n} of {total}<br>'
               f'<span class="k">{esc(tip_prefix)}</span>')
        segs.append(
            f'<div class="seg{dark}" style="width:{pct:.4f}%;background:{color}" '
            f'tabindex="0" role="img" aria-label="{esc(name)}: {n} of {total}" '
            f'data-tip="{esc(tip)}">{inner}</div>')
    return f'<div class="bar-row">{label_html}<div class="bar">{"".join(segs)}</div></div>'


def legend():
    out = []
    for k in ORDER:
        name, icon, color = STATUS[k]
        out.append(f'<span class="chip"><span class="dot" style="background:{color}"></span>'
                   f'{icon} {name}</span>')
    return f'<div class="chips">{"".join(out)}</div>'


APPENDIX_TITLE = {
    "A": "the paper\u2019s proofs",
    "B": "the Silva comparison",
    "H": "the doubling graph",
}

LINKS = [
    ("blueprint/index.html", "The blueprint",
     "leanblueprint\u2019s own site: every result stated in English and sketched, with a "
     "\u2713 where the Lean proof is complete and the declaration named beside it. The "
     "declaration names are not yet links \u2014 there is no doc-gen4 site to point them at."),
    # No card for blueprint/dep_graph_document.html: `web.tex` omits `\\dep_graph` on purpose
    # (the fifteen `main_*` results are siblings, and content.tex carries no `\\uses`), so
    # plasTeX emits that page with zero nodes and zero edges. The graph below is the real one.
    ("lean-graph.svg", "Dependency graph",
     "Drawn from the compiled proof terms rather than from the prose: what each proof actually "
     "invokes, via <code>Expr.getUsedConstants</code>. 44 nodes; a picture, not a navigable map."),
    ("coverage.html", "Coverage",
     "All chartered statements with status, bucket and the Lean files that carry them. "
     "The table behind the bars above."),
    ("sorry-status.html", "Open sorries",
     "Every unproved statement the scaffold holds, keyed and justified. The strict library "
     "never imports it."),
    ("repo-map.html", "Repo map",
     "One line per file, the layer order, and the loose ends \u2014 what to read before "
     "touching anything."),
    ("repo-index.html", "Declaration index",
     "<b>The statement inspector.</b> Every declaration with its full pretty-printed Lean type "
     "\u2014 binders, hypotheses and conclusion as the compiler sees them. Large; use the "
     "browser\u2019s find."),
    ("readme.html", "README",
     "What the project is, where it stands, and the three obstructions it is blocked on."),
    ("print.pdf", "The blueprint, as a paper",
     "The same content typeset \u2014 the draft appendix generated from the development."),
]


def landing(d):
    s = d["statements"]
    n = d["n_statements"]
    pct = round(100.0 * s.get("closed", 0) / n) if n else 0

    tiles = [
        ("\u2705 Closed", s.get("closed", 0), "certified in full"),
        ("\U0001f7e1 Partial", s.get("partial", 0), "some items proved"),
        ("\u2b1c Open", s.get("open", 0), "stated, not proved"),
        ("Open sorries", d["sorries"], "in the scaffold"),
        ("Declarations", f'{d["decls"]:,}', f'across {d["files"]} files'),
    ]
    if s.get("stale"):
        tiles.insert(3, ("\u26a0\ufe0f Stale", s["stale"], "the paper moved under it"))

    tile_html = "".join(
        f'<div class="tile"><p class="label">{lab}</p>'
        f'<div class="value">{val}</div><div class="sub">{sub}</div></div>'
        for lab, val, sub in tiles)

    rows = [bar(s, '<div class="name"><b>All three</b><br>'
                   f'{n} statements</div>', "of the whole charter")]
    for app in sorted(d["per_appendix"]):
        c = d["per_appendix"][app]
        src = d["appendices"].get(app, "")
        rows.append(bar(c, f'<div class="name"><b>Appendix {app}</b><br>'
                           f'{esc(APPENDIX_TITLE.get(app, ""))}</div>',
                        f"Appendix {app} \u2014 {src}"))

    table_rows = "".join(
        f'<tr><td>Appendix {app}</td>'
        + "".join(f'<td class="num">{d["per_appendix"][app].get(k, 0)}</td>' for k in ORDER)
        + f'<td class="num">{sum(d["per_appendix"][app].values())}</td></tr>'
        for app in sorted(d["per_appendix"]))
    table_rows += ('<tr><td><b>Total</b></td>'
                   + "".join(f'<td class="num"><b>{s.get(k, 0)}</b></td>' for k in ORDER)
                   + f'<td class="num"><b>{n}</b></td></tr>')

    cards = "".join(
        f'<a class="card" href="{href}"><div class="t">{esc(t)}</div>'
        f'<div class="d">{dsc}</div></a>' for href, t, dsc in LINKS)

    build = ('<span class="chip"><span class="dot" style="background:var(--status-good)"></span>'
             '\u2705 Build green</span>' if d["build_ok"] else
             '<span class="chip"><span class="dot" style="background:var(--status-critical)">'
             '</span>\u26a0\ufe0f Build not green</span>')
    sorry_chip = (
        '<span class="chip"><span class="dot" style="background:var(--status-good)"></span>'
        '\u2705 Sorry-free</span>' if d["sorries"] == 0 else
        f'<span class="chip"><span class="dot" style="background:var(--status-warning)"></span>'
        f'\U0001f7e1 {d["sorries"]} open sorries</span>')
    dirty = ('<span class="chip"><span class="dot" style="background:var(--status-warning)">'
             '</span>\U0001f7e1 Uncommitted changes</span>' if d["library_dirty"] else "")

    return page("GFNBoundsLean \u2014 blueprint", f"""
<header class="masthead">
  <p class="eyebrow">GFNBoundsLean</p>
  <h1>Universality and Convergence of Generative Flows, certified</h1>
  <p>A Lean&nbsp;4 / Mathlib formalization of the paper\u2019s proofs \u2014 Appendices
     <b>A</b> (the proofs), <b>B</b> (the Silva comparison) and <b>H</b> (the doubling graph).
     Every number on this page is read from the artefacts <code>make check</code> writes.</p>
</header>

<div class="hero">
  <div class="figure">{pct}%</div>
  <div class="caption">of the {n} chartered statements are certified in full \u2014
    {s.get('closed', 0)} closed, {s.get('partial', 0)} partial, {s.get('open', 0)} open.</div>
</div>
<div class="chips">{build}{sorry_chip}{dirty}</div>

<section>
  <h2>Where it stands</h2>
  <div class="tiles">{tile_html}</div>
</section>

<section>
  <h2>By appendix</h2>
  {legend()}
  <div class="bars" style="margin-top:1rem">{"".join(rows)}</div>
  <details>
    <summary>Table view</summary>
    <table>
      <thead><tr><th>Source</th>
        {"".join(f'<th class="num">{STATUS[k][0]}</th>' for k in ORDER)}
        <th class="num">Total</th></tr></thead>
      <tbody>{table_rows}</tbody>
    </table>
  </details>
</section>

<section>
  <h2>Read</h2>
  <div class="links">{cards}</div>
</section>

<footer>
  Built {esc(d["generated"])} from library <code>{esc(d["library_commit"])}</code>
  against paper <code>{esc(d["paper_commit"])}</code>.
  Source: <a href="https://github.com/LBrunswic/GFNBoundsLean">github.com/LBrunswic/GFNBoundsLean</a>
  (private). Machine twin of these numbers: <a href="status.json">status.json</a>.
</footer>
""", extra=THEME_JS + TIP_JS)


# ---------------------------------------------------------------- markdown pages

def render_md(src, dest, title):
    """pandoc gives us a fragment; the local template gives it the site's clothes."""
    p = os.path.join(ROOT, src)
    if not os.path.exists(p):
        return False
    r = sh("pandoc", "--from", "gfm", "--to", "html", "--no-highlight", p)
    if r.returncode != 0:
        sys.stderr.write("pandoc failed on %s:\n%s\n" % (src, r.stderr))
        return False
    body = ('<div class="doc">' + r.stdout + "</div>"
            '<a class="backlink" href="index.html">\u2190 back to the dashboard</a>')
    with open(os.path.join(OUT, dest), "w", encoding="utf-8") as fh:
        fh.write(page(title, body, extra=THEME_JS))
    return True


# ---------------------------------------------------------------- build

def main():
    if shutil.which("pandoc") is None:
        sys.exit("dashboard: pandoc is required (apt install pandoc)")

    d = collect()
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)

    with open(os.path.join(OUT, "dashboard.css"), "w", encoding="utf-8") as fh:
        fh.write(CSS)
    with open(os.path.join(OUT, "index.html"), "w", encoding="utf-8") as fh:
        fh.write(landing(d))
    with open(os.path.join(OUT, "status.json"), "w", encoding="utf-8") as fh:
        json.dump(d, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    missing = []
    for src, dest, title in [
        ("docs/COVERAGE.md", "coverage.html", "Coverage \u2014 GFNBoundsLean"),
        ("docs/SORRY-STATUS.md", "sorry-status.html", "Open sorries \u2014 GFNBoundsLean"),
        ("docs/REPO-MAP.md", "repo-map.html", "Repo map \u2014 GFNBoundsLean"),
        ("docs/REPO-INDEX.md", "repo-index.html", "Declaration index \u2014 GFNBoundsLean"),
        ("README.md", "readme.html", "README \u2014 GFNBoundsLean"),
    ]:
        if not render_md(src, dest, title):
            missing.append(src)

    web = os.path.join(ROOT, "blueprint", "web")
    if os.path.isdir(web) and os.path.exists(os.path.join(web, "index.html")):
        shutil.copytree(web, os.path.join(OUT, "blueprint"))
    else:
        missing.append("blueprint/web (run `make appendix`)")

    for src, dest in [("blueprint/print/print.pdf", "print.pdf"),
                      ("docs/lean-graph.svg", "lean-graph.svg")]:
        p = os.path.join(ROOT, src)
        if os.path.exists(p):
            shutil.copy2(p, os.path.join(OUT, dest))
        else:
            missing.append(src)

    n = d["n_statements"]
    print("dashboard: %d statements (%d closed, %d partial, %d open), %d sorries, %d decls"
          % (n, d["statements"].get("closed", 0), d["statements"].get("partial", 0),
             d["statements"].get("open", 0), d["sorries"], d["decls"]))
    if missing:
        print("dashboard: MISSING -> " + ", ".join(missing))
    return 0


if __name__ == "__main__":
    sys.exit(main())
