#!/usr/bin/env python3
"""The knowledge base: what previous sessions learned, in a form the next one can act on.

`kb/entries/NNNN-slug.md` is one lesson per file. `kb/INDEX.md` is generated from them.

    python3 scripts/kb.py index                 regenerate kb/INDEX.md
    python3 scripts/kb.py lint                  validate every entry (run by `make check`)
    python3 scripts/kb.py search tsum summable   full-text, ranked, prints id/title/tags
    python3 scripts/kb.py new --title "..." --kind pattern --tags tsum,stat [--source F:L]

An entry earns its place by changing what the next session would do. "Lean has `linarith`" does
not. "`Stat.inv` only accepts bounded test functions, so bound before you sum" does.
"""
import argparse, datetime, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KB = os.path.join(ROOT, "kb")
ENTRIES = os.path.join(KB, "entries")

KINDS = {
    "pattern":     "A move that works — reach for it",
    "pitfall":     "A move that looks right and is not",
    "api":         "Where the Mathlib (or local) lemma actually lives",
    "convention":  "A house rule of this library; breaking it fails a gate or a review",
    "obstruction": "A wall that has been hit and named — do not re-attempt without new material",
    "workflow":    "How to drive the build, the audits, or the paper map",
}
CONFIDENCE = ("established", "provisional")
REQUIRED_HEADINGS = ("## When", "## Do")


def parse(path):
    text = open(path, encoding="utf-8").read()
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        return None, text, "no YAML frontmatter"
    meta, body = {}, m.group(2)
    for line in m.group(1).splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        k, _, v = line.partition(":")
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            v = [x.strip() for x in v[1:-1].split(",") if x.strip()]
        meta[k.strip()] = v
    return meta, body, None


def load_all():
    out = []
    if not os.path.isdir(ENTRIES):
        return out
    for n in sorted(os.listdir(ENTRIES)):
        if n.endswith(".md"):
            p = os.path.join(ENTRIES, n)
            meta, body, err = parse(p)
            out.append({"path": p, "file": os.path.relpath(p, ROOT), "meta": meta or {},
                        "body": body, "err": err})
    return out


def cmd_lint(_args):
    entries, bad, seen_ids = load_all(), [], {}
    for e in entries:
        rel = e["file"]
        if e["err"]:
            bad.append("%s: %s" % (rel, e["err"]))
            continue
        m = e["meta"]
        for k in ("id", "title", "kind", "tags", "confidence", "created"):
            if k not in m:
                bad.append("%s: missing frontmatter key `%s`" % (rel, k))
        if m.get("kind") not in KINDS:
            bad.append("%s: kind `%s` is not one of %s" % (rel, m.get("kind"), ", ".join(KINDS)))
        if m.get("confidence") not in CONFIDENCE:
            bad.append("%s: confidence must be one of %s" % (rel, ", ".join(CONFIDENCE)))
        if not isinstance(m.get("tags"), list) or not m.get("tags"):
            bad.append("%s: tags must be a non-empty [a, b] list" % rel)
        i = m.get("id")
        if i in seen_ids:
            bad.append("%s: id %s already used by %s" % (rel, i, seen_ids[i]))
        seen_ids[i] = rel
        if i and not os.path.basename(rel).startswith(str(i) + "-"):
            bad.append("%s: filename must start with the id `%s-`" % (rel, i))
        for h in REQUIRED_HEADINGS:
            if h not in e["body"]:
                bad.append("%s: missing section `%s`" % (rel, h))
        for src in (m.get("sources") or []):
            f = src.split(":")[0]
            if "/" in f and not os.path.exists(os.path.join(ROOT, f)):
                bad.append("%s: source `%s` no longer exists" % (rel, src))
    for e in bad:
        print("FAIL: %s" % e)
    if bad:
        sys.exit(1)
    print("kb lint: %d entries, all well-formed" % len(entries))


def cmd_index(_args):
    entries = [e for e in load_all() if not e["err"]]
    entries.sort(key=lambda e: e["meta"].get("id", ""))
    by_kind, tags = {}, {}
    for e in entries:
        by_kind.setdefault(e["meta"]["kind"], []).append(e)
        for t in e["meta"]["tags"]:
            tags.setdefault(t, []).append(e["meta"]["id"])
    out = ["# Knowledge base index\n",
           "Generated by `scripts/kb.py index`; do not edit by hand. "
           "**%d entries.** How to read and how to add: [`README.md`](README.md).\n" % len(entries)]
    for kind, blurb in KINDS.items():
        if kind not in by_kind:
            continue
        out.append("\n## %s — *%s*\n" % (kind, blurb))
        out.append("| id | title | tags | confidence |\n|---|---|---|---|")
        for e in by_kind[kind]:
            m = e["meta"]
            out.append("| [`%s`](entries/%s) | %s | %s | %s |" % (
                m["id"], os.path.basename(e["path"]), m["title"],
                ", ".join("`%s`" % t for t in m["tags"]),
                "" if m["confidence"] == "established" else "*provisional*"))
    out.append("\n## By tag\n")
    for t in sorted(tags):
        out.append("- **`%s`** — %s" % (t, ", ".join("`%s`" % i for i in sorted(set(tags[t])))))
    out.append("")
    with open(os.path.join(KB, "INDEX.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print("kb index: %d entries, %d tags" % (len(entries), len(tags)))


def cmd_search(args):
    terms = [t.lower() for t in args.terms]
    hits = []
    for e in load_all():
        hay = (json.dumps(e["meta"], ensure_ascii=False) + e["body"]).lower()
        score = sum(hay.count(t) for t in terms)
        if score:
            hits.append((score, e))
    for score, e in sorted(hits, key=lambda x: -x[0]):
        m = e["meta"]
        print("[%s] %-2d  %s\n        %s  tags: %s" % (
            m.get("id", "????"), score, m.get("title", ""), e["file"],
            ", ".join(m.get("tags", []))))
    if not hits:
        print("no entry matches %s" % " ".join(terms))


def cmd_new(args):
    existing = [int(e["meta"].get("id", 0) or 0) for e in load_all()]
    nid = "%04d" % (max(existing or [0]) + 1)
    slug = re.sub(r"[^a-z0-9]+", "-", args.title.lower()).strip("-")[:48]
    path = os.path.join(ENTRIES, "%s-%s.md" % (nid, slug))
    body = """---
id: %s
title: %s
kind: %s
tags: [%s]
confidence: %s
sources: [%s]
created: %s
---

## When

<The situation that should make the next session reach for this. Be concrete about the goal
shape or the error message, not about the mathematics.>

## Do

<The move. Copy-pasteable Lean where possible.>

## Why

<What goes wrong otherwise, or what makes this the right shape here.>
""" % (nid, args.title, args.kind, ", ".join(args.tags.split(",")) if args.tags else "",
       args.confidence, ", ".join(args.source or []),
       datetime.date.today().isoformat())
    os.makedirs(ENTRIES, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)
    print(os.path.relpath(path, ROOT))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("index").set_defaults(fn=cmd_index)
    sub.add_parser("lint").set_defaults(fn=cmd_lint)
    s = sub.add_parser("search")
    s.add_argument("terms", nargs="+")
    s.set_defaults(fn=cmd_search)
    n = sub.add_parser("new")
    n.add_argument("--title", required=True)
    n.add_argument("--kind", required=True, choices=list(KINDS))
    n.add_argument("--tags", default="")
    n.add_argument("--confidence", default="provisional", choices=CONFIDENCE)
    n.add_argument("--source", action="append")
    n.set_defaults(fn=cmd_new)
    a = ap.parse_args()
    a.fn(a)


if __name__ == "__main__":
    main()
