#!/usr/bin/env python3
"""Every `sorry` in `scaffold/` must be tagged, and the list may only shrink.

A tagged sorry looks like

    sorry -- SORRY(prop:doubling_phase): Foster's criterion is not in Mathlib v4.31.0.

Bare sorries are a hard failure: an untagged one is invisible to review. Each is attributed to
the nearest preceding declaration and keyed by `sha1(label + decl)[:8]`, which is stable when
lines move.

  (no flag)   check against docs/sorry-baseline.json; fail if any id is new or the count rose
  --accept    rewrite the baseline (a deliberate, reviewable diff)
"""
import hashlib, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCAFFOLD = os.path.join(ROOT, "scaffold")
DOCS = os.path.join(ROOT, "docs")
BASELINE = os.path.join(DOCS, "sorry-baseline.json")

TAG = re.compile(r"sorry\s*--\s*SORRY\(([a-z]+:[a-z_0-9]*)\)\s*:\s*(\S.*?)\s*$")
DECL = re.compile(r"^\s*(?:@\[[^\]]*\]\s*)?(?:private\s+|protected\s+|noncomputable\s+)*"
                  r"(?:theorem|lemma|def|instance|example)\s+([A-Za-z_][\w.']*)")


def scan():
    found = []
    for dirpath, _, names in os.walk(SCAFFOLD):
        for n in sorted(names):
            if not n.endswith(".lean"):
                continue
            path = os.path.join(dirpath, n)
            rel = os.path.relpath(path, ROOT)
            lines = open(path, encoding="utf-8").read().split("\n")
            decl = "(top level)"
            for i, ln in enumerate(lines, 1):
                d = DECL.match(ln)
                if d:
                    decl = d.group(1)
                if not re.search(r"\bsorry\b", ln):
                    continue
                if ln.lstrip().startswith("--") or ln.lstrip().startswith("/-"):
                    continue          # a mention in prose, not a term
                m = TAG.search(ln)
                if not m:
                    print("FAIL: %s:%d bare `sorry` — tag it "
                          "`sorry -- SORRY(<paper label>): <reason>`" % (rel, i))
                    found.append(None)
                    continue
                label, reason = m.group(1), m.group(2)
                sid = hashlib.sha1(("%s|%s" % (label, decl)).encode()).hexdigest()[:8]
                found.append({"id": sid, "label": label, "decl": decl,
                              "file": rel, "line": i, "reason": reason})
    return found


def main():
    found = scan()
    if any(f is None for f in found):
        sys.exit(1)
    found.sort(key=lambda f: (f["label"], f["decl"]))
    os.makedirs(DOCS, exist_ok=True)

    with open(os.path.join(DOCS, "SORRY-STATUS.md"), "w", encoding="utf-8") as fh:
        fh.write("# Open `sorry`s\n\nGenerated by `scripts/sorry_audit.py`; do not edit by hand.\n\n")
        fh.write("Every entry is a statement of `app_doubling.tex` that this library states but "
                 "does not yet prove. Nothing in the strict library `GFNBounds` depends on any of "
                 "them: `sorry` is a compile error there, and `GFNBounds` never imports "
                 "`GFNBoundsScaffold`.\n\n")
        fh.write("| id | paper label | declaration | file:line | why it is open |\n")
        fh.write("|---|---|---|---|---|\n")
        for f in found:
            fh.write("| `%s` | `%s` | `%s` | `%s:%d` | %s |\n"
                     % (f["id"], f["label"], f["decl"], f["file"], f["line"], f["reason"]))
        fh.write("\n**Total: %d.**\n" % len(found))

    with open(os.path.join(DOCS, "sorry.json"), "w", encoding="utf-8") as fh:
        json.dump(found, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    if "--accept" in sys.argv or not os.path.exists(BASELINE):
        with open(BASELINE, "w", encoding="utf-8") as fh:
            json.dump([{"id": f["id"], "label": f["label"], "decl": f["decl"]} for f in found],
                      fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        print("sorry_audit: baseline written, %d open" % len(found))
        return

    base = json.load(open(BASELINE, encoding="utf-8"))
    base_ids = {b["id"] for b in base}
    new = [f for f in found if f["id"] not in base_ids]
    ok = True
    for f in new:
        print("FAIL: new sorry %s (%s in %s) — the list may only shrink. "
              "If this is intended, `--accept`." % (f["id"], f["label"], f["decl"]))
        ok = False
    if len(found) > len(base):
        print("FAIL: sorry count rose from %d to %d" % (len(base), len(found)))
        ok = False
    if not ok:
        sys.exit(1)
    closed = [b for b in base if b["id"] not in {f["id"] for f in found}]
    for b in closed:
        print("note: closed %s (%s)" % (b["id"], b["label"]))
    print("sorry_audit: %d open (baseline %d)" % (len(found), len(base)))


if __name__ == "__main__":
    main()
